#!/usr/bin/bash

echo "username: ${CFG_DB_USER}"
echo "password: ${CFG_DB_PASS}"

mysql -h ${CFG_DB_HOST} -u ${CFG_DB_USER} -p${CFG_DB_PASS} upsilon < sql/schema.sql
mysql -h ${CFG_DB_HOST} -u ${CFG_DB_USER} -p${CFG_DB_PASS} upsilon < sql/initialData.sql

